# Generated by Django 2.2.1 on 2019-06-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(default='profile-default.jpg', null=True, upload_to=''),
        ),
    ]
