# Generated by Django 2.2.1 on 2019-06-08 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('street', models.CharField(max_length=25)),
                ('building', models.CharField(max_length=4)),
                ('flat', models.IntegerField(blank=True, null=True)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clas_student', to='student.Clas')),
            ],
        ),
    ]
